-   id: fmt
    name: fmt
    description: Format files with Scarb fmt
    entry: scarb fmt
    language: system
    files: \.cairo$
    args: []
-   id: test
    name: cairo test
    description: Run tests with Scarb test
    entry: scarb test
    language: system
    args: []